---
- hosts: docker
  become: true

  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Install requirement for docker
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present


    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/debian bullseye stable"
        state: present


    - name : Update apt and install docker-ce
      apt:
          update_cache: yes
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
          state: latest
    - name: Install docker-compose from official github repo
      get_url:
        url : https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'
